# Upload the steps using or include other templates
name: build app - cookiecutter template

on:
  push

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build cookiecutter
        uses: ./.github/actions/build-cookiecutter
        with:
          is_main: true 
          repo_name: app-java
          template: cookiecutter-java
          working_directory: .
  
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build cookiecutter - ruby
        uses: ./.github/actions/build-cookiecutter
        with:
          is_main: false 
          repo_name: app-java
          template: cookiecutter-ruby
          working_directory: .

      - name: Notification cookiecutter 
        shell: bash
        working-directory: .
        run: |
          ls
          echo "Terminando la creacion"
  
  # create-repo:
  #  pending step PR
 